package com.softwareengineering;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cache.annotation.EnableCaching;

// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@EnableCaching
@SpringBootApplication
public class SoftwareEngineeringApplication {

    public static void main(String[] args) {
        SpringApplication.run(SoftwareEngineeringApplication.class, args);
    }

}
